### ISSUE TITLE
Docker push error

### ISSUE THREAD

**Issue by amit-timalsina** [aws-samples/amazon-sagemaker-mlflow-fargate#5]
`[100%] fail: docker push 031342435657.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-031342435657-us-east-1:df0c2dd130fbc264a70d9331a9a4367b68d888ce0d1a851cc223b5f794dbc7f1 exited with error code 1: EOF

 ❌  DeploymentStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/Users/amittimalsina/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CloudFormationDeployments.publishStackAssets (/Users/amittimalsina/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:424:7)
    at CloudFormationDeployments.deployStack (/Users/amittimalsina/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:317:5)
    at CdkToolkit.deploy (/Users/amittimalsina/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:201:24)
    at initCommandLine (/Users/amittimalsina/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/bin/cdk.ts:281:9)
Failed to publish one or more assets. See the error messages above for more information.`

Can you please help me how i can solve this?

**Comment by harrysalmon** [comment]
Having the same issue: 

Mac

Software:

    System Software Overview:

      System Version: macOS 11.6.1 (20G224)
      Kernel Version: Darwin 20.6.0
...

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 12 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
...

Node:
v16.3.0

aws cli 
aws-cli/2.3.5 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off

**Comment by SofianHamiti** [comment]
Thanks @harrysalmon
@amit-timalsina - can you confirm if it works with Docker on your machine?
